### ISSUE TITLE
Error inserting Empatica S/N

### ISSUE THREAD

**Issue by fnobilia** [RADAR-CNS/RADAR-AndroidApplication#10]
If you try to insert 123456789 as S/N the app crashes and cannot be used anymore. The only way to use it again is to reinstall. 
11-18 14:07:27.529 6909-6909/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: org.radarcns.android.android, PID: 6909
                                                 java.lang.RuntimeException: Unable to start service org.radarcns.empaticaE4.E4Service@5ff6337 with null: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.hasExtra(java.lang.String)' on a null object reference
                                                     at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3008)
                                                     at android.app.ActivityThread.-wrap17(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1423)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5488)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)
                                                  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.hasExtra(java.lang.String)' on a null object reference
                                                     at org.radarcns.android.DeviceService.onInvocation(DeviceService.java:381)
                                                     at org.radarcns.empaticaE4.E4Service.onInvocation(E4Service.java:63)
                                                     at org.radarcns.android.DeviceService.onStartCommand(DeviceService.java:122)
                                                     at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2991)
                                                     at android.app.ActivityThread.-wrap17(ActivityThread.java) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1423) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:148) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5488) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)

**Comment by MaximMoinat** [comment]
We replicated the problem.
For now, please connect without entering a serial number. The app will scan for any E4 if the field is left as it is. (in other words: the field is not required yet)

**Comment by MaximMoinat** [comment]
Fixed in the dev branch.
