### ISSUE TITLE
Fatal Exception: GoogleApiHandler on launch

### ISSUE THREAD

**Issue by sboettcher** [RADAR-CNS/RADAR-AndroidApplication#45]
Having problems starting the app (restructuring branch) on our dev tablet (Android 6.0.1, Kernel 3.14.55), it immediately fails with exception:

<pre>org.radarcns.android.android E/AndroidRuntime: FATAL EXCEPTION: GoogleApiHandler
    Process: org.radarcns.android.android, PID: 11930
    java.lang.NoSuchMethodError: No static method zzz(Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/internal/zzaa; or its super classes (declaration of 'com.google.android.gms.common.internal.zzaa' appears in /data/app/org.radarcns.android.android-2/base.apk)
        at com.google.android.gms.measurement.internal.zzx.zzbd(Unknown Source)
        at com.google.android.gms.measurement.AppMeasurement.getInstance(Unknown Source)
        at com.google.android.gms.internal.zzadd.zzaR(Unknown Source)
        at com.google.android.gms.internal.zzadd.zzaS(Unknown Source)
        at com.google.android.gms.internal.zzade$1.zza(Unknown Source)
        at com.google.android.gms.internal.zzade$zzb.zza(Unknown Source)
        at com.google.android.gms.internal.zzade$zzb.zza(Unknown Source)
        at com.google.android.gms.internal.zzzv$zza.zzb(Unknown Source)
        at com.google.android.gms.internal.zzzq$zzb.zza(Unknown Source)
        at com.google.android.gms.internal.zzaap$zza.zzb(Unknown Source)
        at com.google.android.gms.internal.zzaap$zza.zzwb(Unknown Source)
        at com.google.android.gms.internal.zzaap$zza.zzvZ(Unknown Source)
        at com.google.android.gms.internal.zzaap$zza.onConnected(Unknown Source)
        at com.google.android.gms.common.internal.zzl$1.onConnected(Unknown Source)
        at com.google.android.gms.common.internal.zzf$zzj.zzwZ(Unknown Source)
        at com.google.android.gms.common.internal.zzf$zza.zzc(Unknown Source)
        at com.google.android.gms.common.internal.zzf$zza.zzu(Unknown Source)
        at com.google.android.gms.common.internal.zzf$zze.zzxa(Unknown Source)
        at com.google.android.gms.common.internal.zzf$zzd.handleMessage(Unknown Source)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)</pre>

It works fine on an Udoo Neo (Android 6.0.1, Kernel 3.14.52, No Google Play Services installed), however that is a bit cumbersome for testing things out on.
The app has worked fine on the tablet, before the restructuring changes.
I've googled a bit and found that this error might happen when google play services dependencies aren't the same version throughout the projectm however I have not found a solution.

Also getting an error in `app/build.gradle` at 

><code>compile 'com.android.support:appcompat-v7:22.2.0'</code>

telling me that "All com.android.support libraries must use the exact same version specification..." however building works without a hitch. Not sure if that is related.

**Comment by fnobilia** [comment]
@blootsvoets and myself were checking the issue on `app/build.gradle`. It could be related to some hidden dependencies.

**Comment by blootsvoets** [comment]
I've added an explicit dependency to firebase 10.0.1 in f29877f, before gradle was complaining that google couldn't detect the firebase version, and this seems to fix that. Could you check if that fixes your issue as well? (not the Android Studio warning, but the exception)

When we go to ambulatory trials, I think we should just move to the latest version of Android for our build target. That would mean that users get notifications based on the permissions that we require, BUT, at least the code is then well supported. There isn't any firebase version available anymore that depends on Android API 22. The oldest version I have available is 9.0.0, which depends on Android API 23.

**Comment by sboettcher** [comment]
https://github.com/RADAR-CNS/RADAR-AndroidApplication/commit/f29877f68cf560d69222677b0d8f71c2e6985de5 fixed the exception, thanks!
